function [ frhs ] = matEvaluateStrongFormEdgeRHS( obj, fluxM, fluxP, fluxS )

% frhs = mxEvaluateStrongFormEdgeRHS( ...
%     obj.mesh.cell.invM, obj.M, ...
%     obj.FToE, obj.FToF, obj.FToN1, obj.FToN2, ...
%     obj.Js, obj.mesh.J, fluxM, fluxP, fluxS, obj.mesh.cell.Nface );

frhs = mxEvaluateStrongFromEdgeRHS( ...
    obj.mesh.cell.invM, obj.M, ...
    obj.FToE, obj.FToN1, obj.FToN2, ...
    obj.Js, obj.mesh.J, fluxM, fluxP, fluxS );

end
