function [ frhs ] = matEvaluateStrongFormEdgeRHS( obj, fluxM, fluxP, fluxS )

frhs = mxEvaluateStrongFromEdgeRHS( ...
    obj.mesh.cell.invM, obj.M, ...
    obj.FToE, obj.FToF, obj.FToN1, obj.FToN2, ...
    obj.Js, obj.mesh.J, fluxM, fluxP, fluxS, obj.mesh.cell.Nface );

end
