function matSetInitializeCharacteristicMatrix( obj, EdgeType, meshUnion )

obj.SPNPX = mxSecondOrderDerivAboutNohydroPressInHorizon( meshUnion.cell.Np,...
    meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
    meshUnion.EToE, meshUnion.InnerEdge.FToE, meshUnion.InnerEdge.FToF,...
    meshUnion.InnerEdge.FToN1, meshUnion.InnerEdge.FToN2, meshUnion.LAV,...
    meshUnion.InnerEdge.Js,...
    meshUnion.InnerEdge.M, meshUnion.BoundaryEdge.Ne , meshUnion.InnerEdge.Ne, ...
    meshUnion.InnerEdge.LAV, meshUnion.cell.Fmask, meshUnion.cell.Nfp, meshUnion.cell.N,...
    meshUnion.InnerEdge.nx, meshUnion.rx, meshUnion.sx, meshUnion.cell.Dr, meshUnion.cell.Ds,...
    meshUnion.BottomEdge.LAV, meshUnion.BottomEdge.Ne, meshUnion.BottomEdge.FToE,...
    meshUnion.SurfaceBoundaryEdge.LAV, meshUnion.SurfaceBoundaryEdge.Ne, ...
    meshUnion.SurfaceBoundaryEdge.FToE, meshUnion.SurfaceBoundaryEdge.M, ...
    meshUnion.SurfaceBoundaryEdge.Js, EdgeType, meshUnion.J, meshUnion.cell.M, ...
    meshUnion.BottomEdge.FToN1, meshUnion.BottomEdge.FToN2);

obj.SPNPY = mxSecondOrderDerivAboutNohydroPressInHorizon( meshUnion.cell.Np,...
    meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
    meshUnion.EToE, meshUnion.InnerEdge.FToE, meshUnion.InnerEdge.FToF,...
    meshUnion.InnerEdge.FToN1, meshUnion.InnerEdge.FToN2, meshUnion.LAV,...
    meshUnion.InnerEdge.Js, ...
    meshUnion.InnerEdge.M, meshUnion.BoundaryEdge.Ne , meshUnion.InnerEdge.Ne, ...
    meshUnion.InnerEdge.LAV, meshUnion.cell.Fmask, meshUnion.cell.Nfp, meshUnion.cell.N,...
    meshUnion.InnerEdge.ny, meshUnion.ry, meshUnion.sy, meshUnion.cell.Dr, meshUnion.cell.Ds,...
    meshUnion.BottomEdge.LAV, meshUnion.BottomEdge.Ne, meshUnion.BottomEdge.FToE,...
    meshUnion.SurfaceBoundaryEdge.LAV, meshUnion.SurfaceBoundaryEdge.Ne,...
    meshUnion.SurfaceBoundaryEdge.FToE, meshUnion.SurfaceBoundaryEdge.M, ...
    meshUnion.SurfaceBoundaryEdge.Js, EdgeType, meshUnion.J, meshUnion.cell.M, ...
    meshUnion.BottomEdge.FToN1, meshUnion.BottomEdge.FToN2);

%     obj.SPNPS = mxSecondOrderDerivAboutNohydroPressInVert( meshUnion.cell.Np,...
%         meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
%         meshUnion.EToE, meshUnion.tz, meshUnion.cell.Dt, meshUnion.J, meshUnion.mesh2d.J,...
%         meshUnion.mesh2d.cell.M, meshUnion.cell.M, meshUnion.cell.Fmask, meshUnion.cell.Nfp,...
%         meshUnion.cell.N);
%
obj.PNPS = mxFirstOrderDerivAboutNohydroPressInVert( meshUnion.cell.Np,...
    meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
    meshUnion.EToE, meshUnion.tz, meshUnion.cell.Dt, meshUnion.J, meshUnion.mesh2d.J,...
    meshUnion.mesh2d.cell.M, meshUnion.cell.M, meshUnion.cell.Fmask, meshUnion.cell.Nfp, ...
    meshUnion.BottomEdge.FToE, meshUnion.BottomEdge.FToN1, meshUnion.BottomEdge.FToN2);

obj.PNPX = mxFirstOrderDerivAboutNohydroPressInHorizontal( meshUnion.cell.Np,...
    meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
    meshUnion.EToE, meshUnion.InnerEdge.FToE, meshUnion.InnerEdge.FToF,...
    meshUnion.InnerEdge.FToN1, meshUnion.InnerEdge.FToN2, meshUnion.J, ...
    meshUnion.InnerEdge.Js, meshUnion.cell.M, meshUnion.InnerEdge.M, ...
    meshUnion.InnerEdge.Ne, meshUnion.cell.Nfp, meshUnion.InnerEdge.nx,...
    meshUnion.rx, meshUnion.sx, meshUnion.cell.Dr, meshUnion.cell.Ds,...
    meshUnion.cell.Fmask);

obj.PNPY = mxFirstOrderDerivAboutNohydroPressInHorizontal( meshUnion.cell.Np,...
    meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
    meshUnion.EToE, meshUnion.InnerEdge.FToE, meshUnion.InnerEdge.FToF,...
    meshUnion.InnerEdge.FToN1, meshUnion.InnerEdge.FToN2, meshUnion.J, ...
    meshUnion.InnerEdge.Js, meshUnion.cell.M, meshUnion.InnerEdge.M, ...
    meshUnion.InnerEdge.Ne, meshUnion.cell.Nfp, meshUnion.InnerEdge.ny,...
    meshUnion.ry, meshUnion.sy, meshUnion.cell.Dr, meshUnion.cell.Ds,...
    meshUnion.cell.Fmask);
%
%     obj.MSPNPX = mxMixedSecondOrderDerivAboutNonhydroStaticPressureUpdatedNewVer(meshUnion.cell.Np,...
%         meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
%         meshUnion.EToE, meshUnion.InnerEdge.FToE, meshUnion.InnerEdge.FToF,...
%         meshUnion.InnerEdge.FToN1, meshUnion.InnerEdge.FToN2, meshUnion.LAV, ...
%         meshUnion.J, meshUnion.mesh2d.J, meshUnion.InnerEdge.Js,...
%         meshUnion.cell.M, meshUnion.InnerEdge.M, meshUnion.mesh2d.cell.M, ...
%         meshUnion.BoundaryEdge.Ne , meshUnion.InnerEdge.Ne, meshUnion.InnerEdge.LAV, ...
%         meshUnion.cell.Fmask, meshUnion.cell.Nfp, meshUnion.cell.N, meshUnion.InnerEdge.nx,...
%         meshUnion.rx, meshUnion.sx, meshUnion.tz, meshUnion.cell.Dr, meshUnion.cell.Ds,...
%         meshUnion.cell.Dt, meshUnion.BoundaryEdge.FToF, meshUnion.BoundaryEdge.FToE, ...
%         meshUnion.BoundaryEdge.nx, meshUnion.BoundaryEdge.Js, meshUnion.BottomEdge.LAV, ...
%         meshUnion.BottomEdge.Ne, meshUnion.BottomEdge.FToE, meshUnion.BottomEdge.FToF,...
%         meshUnion.SurfaceBoundaryEdge.LAV, meshUnion.SurfaceBoundaryEdge.Ne, meshUnion.SurfaceBoundaryEdge.FToE);
%
%     obj.MSPNPY = mxMixedSecondOrderDerivAboutNonhydroStaticPressureUpdatedNewVer(meshUnion.cell.Np,...
%         meshUnion.K, meshUnion.Nz, meshUnion.mesh2d.K, meshUnion.cell.Nface,...
%         meshUnion.EToE, meshUnion.InnerEdge.FToE, meshUnion.InnerEdge.FToF,...
%         meshUnion.InnerEdge.FToN1, meshUnion.InnerEdge.FToN2, meshUnion.LAV,...
%         meshUnion.J, meshUnion.mesh2d.J, meshUnion.InnerEdge.Js,...
%         meshUnion.cell.M, meshUnion.InnerEdge.M, meshUnion.mesh2d.cell.M, ...
%         meshUnion.BoundaryEdge.Ne , meshUnion.InnerEdge.Ne, meshUnion.InnerEdge.LAV, ...
%         meshUnion.cell.Fmask, meshUnion.cell.Nfp, meshUnion.cell.N, meshUnion.InnerEdge.ny,...
%         meshUnion.ry, meshUnion.sy, meshUnion.tz, meshUnion.cell.Dr, meshUnion.cell.Ds,...
%         meshUnion.cell.Dt, meshUnion.BoundaryEdge.FToF, meshUnion.BoundaryEdge.FToE, ...
%         meshUnion.BoundaryEdge.ny, meshUnion.BoundaryEdge.Js, meshUnion.BottomEdge.LAV, ...
%         meshUnion.BottomEdge.Ne, meshUnion.BottomEdge.FToE, meshUnion.BottomEdge.FToF,...
%         meshUnion.SurfaceBoundaryEdge.LAV, meshUnion.SurfaceBoundaryEdge.Ne, meshUnion.SurfaceBoundaryEdge.FToE);
end