function frhs2d_VolumeTerm = matEvaluate2dHorizonPCEVolumeTerm( obj, mesh2d, fphys2d )

frhs2d_VolumeTerm(:, :, 1) = -( ...
    mesh2d.rx .* ( mesh2d.cell.Dr * fphys2d(:, :, 2) ) + ...
    mesh2d.sx .* ( mesh2d.cell.Ds * fphys2d(:, :, 2) ) + ...
    mesh2d.ry .* ( mesh2d.cell.Dr * fphys2d(:, :, 3) ) + ...
    mesh2d.sy .* ( mesh2d.cell.Ds * fphys2d(:, :, 3) ) );

end