function [ VolumeIntegralX, VolumeIntegralY ] = matFluxVolumeIntegral(obj, VariableX, VariableY)

GVariableX = obj.Vq{1} * VariableX;
GVariableY = obj.Vq{1} * VariableY;

VolumeIntegralX = ...
    - obj.Dr{1} * ( obj.rxwJ{1} .* GVariableX ) ...
    - obj.Ds{1} * ( obj.sxwJ{1} .* GVariableX ) ...
    - obj.Dt{1} * ( obj.txwJ{1} .* GVariableX );

VolumeIntegralY =  ...
    - obj.Dr{1} * ( obj.rywJ{1} .* GVariableY ) ...
    - obj.Ds{1} * ( obj.sywJ{1} .* GVariableY ) ...
    - obj.Dt{1} * ( obj.tywJ{1} .* GVariableY );

end