function [ frhs ] = matEvaluateStrongFormEdgeRHS( obj, fluxM, fluxS )

frhs = mxEvaluateStrongFormEdgeRHS( ...
    obj.mesh.cell.invM, obj.M, ...
    obj.FToE, obj.FToF, obj.FToN1, ...
    obj.Js, obj.mesh.J, fluxM, fluxS, obj.mesh.cell.Nface );
end

